# Generated by Django 4.0.3 on 2022-10-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessAplication', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
