# Generated by Django 4.0.3 on 2022-10-20 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessAplication', '0005_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UsuarioPersonalizado',
        ),
    ]
