# Generated by Django 4.0.3 on 2022-10-20 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accessAplication', '0008_seccion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
