# Generated by Django 4.0.3 on 2022-10-20 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessAplication', '0009_delete_seccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='familiaApellidos',
            field=models.CharField(max_length=120, null=True),
        ),
    ]
