# Generated by Django 4.0.3 on 2022-10-11 19:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('description', models.TextField(default='', max_length=3000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_responsables', models.IntegerField(default=1)),
                ('num_participantes', models.IntegerField(default=2)),
                ('tipo_actividad', models.CharField(default='', max_length=100)),
                ('image', models.ImageField(default='', upload_to='images/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
