# Generated by Django 4.0.3 on 2022-10-11 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0004_remove_activity_image_activity_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Activity',
        ),
    ]
