# Generated by Django 4.0.3 on 2022-10-11 22:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Actividades', '0009_activity_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='description',
            field=models.TextField(max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='files',
            field=models.FileField(null=True, upload_to='Actividades/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=models.ImageField(null=True, upload_to='Actividades/'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='tipo_actividad',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='titulo',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='ProgramaActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, null=True)),
                ('description', models.TextField(max_length=3000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('num_responsables', models.IntegerField(default=1)),
                ('num_participantes', models.IntegerField(default=2)),
                ('tipo_actividad', models.CharField(max_length=100, null=True)),
                ('images', models.ImageField(null=True, upload_to='Actividades/')),
                ('files', models.FileField(null=True, upload_to='Actividades/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
