# Generated by Django 4.0.3 on 2022-10-12 07:29

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0010_alter_activity_description_alter_activity_files_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AlterField(
            model_name='activity',
            name='num_participantes',
            field=models.IntegerField(default=2, verbose_name='Participantes mínimos Actividad'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='num_responsables',
            field=models.IntegerField(default=1, verbose_name='Responsables mínimos Actividad'),
        ),
        migrations.DeleteModel(
            name='ProgramaActivity',
        ),
        migrations.AddField(
            model_name='photoactivity',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Actividades.activity'),
        ),
    ]
