# Generated by Django 4.0.3 on 2022-10-12 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0011_photoactivity_alter_activity_num_participantes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoactivity',
            name='photo',
            field=models.ImageField(null=True, upload_to='Actividades/'),
        ),
    ]
