# Generated by Django 4.0.3 on 2022-10-12 14:16

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0016_alter_activity_files_alter_activity_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photoactivity',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
