# Generated by Django 4.0.3 on 2022-10-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0021_alter_activity_files_alter_activity_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='files',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
        migrations.AlterField(
            model_name='activity',
            name='num_participantes',
            field=models.IntegerField(default=2, verbose_name='NParticipantes'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='num_responsables',
            field=models.IntegerField(default=1, verbose_name='NResponsables'),
        ),
    ]
