# Generated by Django 4.0.3 on 2022-10-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0022_remove_activity_files_remove_activity_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='files',
            field=models.FileField(default='', upload_to='Actividades/'),
        ),
        migrations.AddField(
            model_name='activity',
            name='images',
            field=models.ImageField(default='', upload_to='Actividades/'),
        ),
    ]
