# Generated by Django 4.0.3 on 2022-10-12 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0023_activity_files_activity_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='files',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
    ]
