# Generated by Django 4.0.3 on 2022-10-13 15:48

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0025_activity_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='photo',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='files',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
