# Generated by Django 4.0.3 on 2022-10-13 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0026_activity_photo_alter_activity_files'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='photo',
            new_name='images',
        ),
    ]
