# Generated by Django 4.0.3 on 2022-10-13 15:52

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0028_alter_activity_files_alter_activity_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='files',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='images',
            field=cloudinary.models.CloudinaryField(max_length=255, null=True),
        ),
    ]
