# Generated by Django 4.0.3 on 2022-10-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0029_alter_activity_files_alter_activity_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='images',
        ),
        migrations.AlterField(
            model_name='activity',
            name='files',
            field=models.FileField(default='', upload_to='Actividades/'),
        ),
    ]
