# Generated by Django 4.0.3 on 2022-10-13 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0030_remove_activity_images_alter_activity_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='files',
        ),
    ]
