# Generated by Django 4.0.3 on 2022-10-13 17:29

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0032_activity_files'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='files_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to=''),
        ),
    ]
