# Generated by Django 4.0.3 on 2022-10-13 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0034_alter_activity_files_alter_activity_files_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='fecha_evaluacion',
            field=models.DateField(null=True),
        ),
    ]
