# Generated by Django 4.0.3 on 2022-10-14 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0038_activity_realizada_alter_activity_files'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='realizada',
        ),
    ]
