# Generated by Django 4.0.3 on 2022-10-20 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0040_activity_realizada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photoactivity',
            name='photoName',
        ),
    ]
