# Generated by Django 4.0.3 on 2022-10-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actividades', '0041_remove_photoactivity_photoname'),
    ]

    operations = [
        migrations.AddField(
            model_name='photoactivity',
            name='photoName',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
