# Generated by Django 4.0.3 on 2022-10-21 14:12

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200, null=True)),
                ('materialDescription', models.TextField(max_length=3000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipoMaterial', models.CharField(max_length=100, null=True)),
                ('fecha_compra', models.DateTimeField(blank=True, null=True)),
                ('factura', models.FileField(blank=True, null=True, upload_to='Materiales/')),
                ('user', models.CharField(max_length=100, null=True)),
                ('fotografia', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Actividades/')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRevision', models.DateTimeField(blank=True, null=True)),
                ('descripcionRevision', models.TextField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Actividades/')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.revisionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material')),
            ],
        ),
    ]
