# Generated by Django 4.0.3 on 2022-10-22 11:36

import Material.models
import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import imagekit.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Asociados', '0002_rename_user_equiposronda_scouters'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsignacionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaAsignacion', models.DateField(blank=True, max_length=100, null=True)),
                ('rondaSolar', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=200, null=True)),
                ('materialDescription', models.TextField(max_length=3000, null=True)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('factura', models.FileField(blank=True, null=True, upload_to=Material.models.uploadFileName)),
                ('alarma', models.BooleanField(default=False)),
                ('User', models.CharField(blank=True, choices=[('1', '1'), ('a52hepof', 'a52hepof'), ('adios', 'adios'), ('admin', 'admin'), ('d', 'd'), ('fernando', 'fernando'), ('hola', 'hola'), ('m92rorum', 'm92rorum')], max_length=50, null=True)),
                ('fotografia', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Material.models.uploadFileName)),
                ('seccion', models.ManyToManyField(through='Material.AsignacionMaterial', to='Asociados.seccion')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaRevision', models.DateTimeField(blank=True, null=True)),
                ('responsableRevision', models.CharField(blank=True, max_length=60, null=True)),
                ('estadoMastiles', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoCubeta', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoDobleTecho', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoEnganches', models.CharField(blank=True, max_length=200, null=True)),
                ('estadoBolsas', models.CharField(blank=True, max_length=200, null=True)),
                ('numPiquetasUltraForte', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numPiquetasForte', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('numPiquetasgEnerals', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seGuardaSucia', models.BooleanField(default=False)),
                ('descripcionRevision', models.TextField(blank=True, null=True)),
                ('desperfectosReparadosLimpios', models.BooleanField(default=False)),
                ('fechaCierre', models.DateField(blank=True, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoRevision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Materiales/')),
                ('revision', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.revisionmaterial')),
            ],
        ),
        migrations.CreateModel(
            name='PhotoMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoName', models.CharField(blank=True, max_length=200, null=True)),
                ('photo', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material')),
            ],
        ),
        migrations.AddField(
            model_name='asignacionmaterial',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Material.material'),
        ),
        migrations.AddField(
            model_name='asignacionmaterial',
            name='seccionName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Asociados.seccion'),
        ),
    ]
