# Generated by Django 4.0.3 on 2022-10-22 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photomaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='photorevision',
            name='revision',
        ),
        migrations.RemoveField(
            model_name='revisionmaterial',
            name='material',
        ),
        migrations.RemoveField(
            model_name='material',
            name='seccion',
        ),
        migrations.DeleteModel(
            name='AsignacionMaterial',
        ),
        migrations.DeleteModel(
            name='PhotoMaterial',
        ),
        migrations.DeleteModel(
            name='PhotoRevision',
        ),
        migrations.DeleteModel(
            name='RevisionMaterial',
        ),
    ]
