# Generated by Django 4.0.3 on 2022-10-22 08:18

import Material.models
from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='user',
        ),
        migrations.AddField(
            model_name='material',
            name='User',
            field=models.CharField(choices=[(0, '1'), (1, 'a52hepof'), (2, 'adios'), (3, 'admin'), (4, 'd'), (5, 'fernando'), (6, 'hola'), (7, 'm92rorum')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='material',
            name='estado',
            field=models.CharField(default='Nuevo', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='factura',
            field=models.FileField(blank=True, null=True, upload_to=Material.models.uploadFileName),
        ),
        migrations.AlterField(
            model_name='material',
            name='fotografia',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to=Material.models.uploadFileName),
        ),
        migrations.AlterField(
            model_name='photorevision',
            name='photo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='Materiales/'),
        ),
    ]
