# Generated by Django 4.0.3 on 2022-10-22 08:57

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0002_remove_material_user_material_user_material_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='alarma',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='User',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '1'), (1, 'a52hepof'), (2, 'adios'), (3, 'admin'), (4, 'd'), (5, 'fernando'), (6, 'hola'), (7, 'm92rorum')], null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Nuevo'), (2, 'Desperfectos menores'), (3, 'Desperfectos moderados'), (4, 'Desperfectos graves')], default='Nuevo', null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipoMaterial',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Tiendas'), (2, 'Recambios tiendas'), (3, 'Campismo'), (4, 'Herramientas'), (5, 'Pinturas'), (6, 'Electricidad'), (7, 'Fontanería'), (8, 'Mesas y bancos'), (9, 'Infraestructura'), (39, 'Otros campismo'), (40, 'Cocina'), (41, 'Hornillos y roscos'), (42, 'Bombonas y cartuchos'), (49, 'Otros cocina'), (50, 'Didáctico'), (51, 'Otros didáctico'), (90, 'Recambios campismo'), (91, 'Recambios electricidad'), (92, 'Recambios fontanería'), (94, 'Recambios cocina')], null=True),
        ),
        migrations.AlterField(
            model_name='photomaterial',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
