# Generated by Django 4.0.3 on 2022-10-22 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0003_material_alarma_alter_material_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='revisionmaterial',
            name='desperfectosReparados',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='estadoBolsas',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='estadoCubeta',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='estadoDobleTecho',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='estadoEnganches',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='estadoMastiles',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='fechaCierre',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='numPiquetasForte',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='numPiquetasUltraForte',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='numPiquetasgEnerals',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='responsableRevision',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, '1'), (1, 'a52hepof'), (2, 'adios'), (3, 'admin'), (4, 'd'), (5, 'fernando'), (6, 'hola'), (7, 'm92rorum')], null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='resultadoRevision',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Revisión conforme'), (2, 'Desperfectos menores, reparaciones no urgentes'), (5, 'Necesita reparación')], null=True),
        ),
        migrations.AddField(
            model_name='revisionmaterial',
            name='seGuardaSucia',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='material',
            name='alarma',
            field=models.BooleanField(default=False),
        ),
    ]
