# Generated by Django 4.0.3 on 2022-10-22 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0003_asignacionmaterial_material_seccion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='seccion',
        ),
        migrations.DeleteModel(
            name='AsignacionMaterial',
        ),
        migrations.DeleteModel(
            name='Material',
        ),
    ]
