# Generated by Django 4.0.3 on 2022-10-22 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0004_revisionmaterial_desperfectosreparados_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='revisionmaterial',
            old_name='desperfectosReparados',
            new_name='desperfectosReparadosLimpios',
        ),
        migrations.AlterField(
            model_name='revisionmaterial',
            name='resultadoRevision',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Revisión conforme'), (2, 'Desperfectos menores, reparaciones no urgentes'), (2, 'Necesita limpieza'), (5, 'Necesita reparación')], null=True),
        ),
    ]
