# Generated by Django 4.0.3 on 2022-10-22 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0005_rename_desperfectosreparados_revisionmaterial_desperfectosreparadoslimpios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='revisionmaterial',
            name='responsableRevision',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
