# Generated by Django 4.0.3 on 2022-10-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Material', '0007_asignacionmaterial_material_seccion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='User',
            field=models.CharField(blank=True, choices=[('1', '1'), ('a52hepof', 'a52hepof'), ('adios', 'adios'), ('admin', 'admin'), ('d', 'd'), ('fernando', 'fernando'), ('hola', 'hola'), ('m92rorum', 'm92rorum')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='estado',
            field=models.CharField(choices=[('Nuevo', 'Nuevo'), ('Desperfectos menores', 'Desperfectos menores'), ('Desperfectos moderados', 'Desperfectos moderados'), ('Desperfectos graves', 'Desperfectos graves')], default='Nuevo', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='tipoMaterial',
            field=models.CharField(blank=True, choices=[('Tiendas', 'Tiendas'), ('Recambios Tiendas', 'Recambios tiendas'), ('Campismo', 'Campismo'), ('Herramientas', 'Herramientas'), ('Pinturas', 'Pinturas'), ('Electricidad', 'Electricidad'), ('Fontanería', 'Fontanería'), ('Mesas y Bancos', 'Mesas y bancos'), ('Infraestructura Acampadas', 'Infraestructura'), ('Otros Campismo', 'Otros campismo'), ('Cocina', 'Cocina'), ('Hornillos y Roscos', 'Hornillos y roscos'), ('Bombonas y Cartuchos', 'Bombonas y cartuchos'), ('Otros Cocina', 'Otros cocina'), ('Didáctico', 'Didáctico'), ('Otros Didáctico', 'Otros didáctico'), ('Recambios campismo', 'Recambios campismo'), ('Recambios electricidad', 'Recambios electricidad'), ('Recambios fontanería', 'Recambios fontanería'), ('Recambios cocina', 'Recambios cocina')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='revisionmaterial',
            name='resultadoRevision',
            field=models.CharField(blank=True, choices=[('pasa revision', 'Revisión conforme'), ('Desperfectos menores', 'Desperfectos menores, reparaciones no urgentes'), ('Necesita limpieza', 'Necesita limpieza'), ('Necesita reparacion', 'Necesita reparación')], max_length=50, null=True),
        ),
    ]
