# Generated by Django 4.0.3 on 2022-10-22 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asociados', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equiposronda',
            old_name='user',
            new_name='scouters',
        ),
    ]
